/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacks.queues;

import java.util.Arrays;

public class App {


    public static void main(String[] args) {
        Stack newStack = new Stack();
        System.out.println(newStack.pop());
        newStack.push(1);
        System.out.println(newStack.toString());
        newStack.push(1);
        newStack.push(3);
        System.out.println(newStack);
        System.out.println(newStack.pop());
        System.out.println(newStack);
        newStack.push(6);
        System.out.println(newStack.peek());
        System.out.println(newStack.isEmpty());

        Queue newQueue = new Queue();
        System.out.println(newQueue.isEmpty());
        newQueue.enqueue(10);
        newQueue.enqueue(5);
        newQueue.enqueue(30);
        System.out.println(newQueue.dequeue());
        System.out.println(newQueue.back.getValue());
        System.out.println(newQueue.front.getValue());
        System.out.println(newQueue);
        System.out.println(newQueue.peek());
        System.out.println(newQueue.isEmpty());

    }
}
