/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    hashTable hashTable = new hashTable(10);
    @Test void add(){
        hashTable.add("10", 10);
        hashTable.add("20", 20);
        assertTrue( hashTable.contains("10"));
        assertFalse(hashTable.contains("5"));
        assertEquals(20,hashTable.get("20"));

    }
    @Test void colission(){
        hashTable.add("Cat", 123);
        hashTable.add("taC", 999);
        System.out.println(hashTable.get("Cat"));
        System.out.println(hashTable.contains("Cat"));
    }
    @Test void hashing(){
        assertEquals(0,hashTable.hash("Cat"));
    }
    @Test void nullKey(){
        assertEquals(null,hashTable.get("ahmed"));
    }
}
