/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

public class Library {
    public static void main(String[] args) {
        int[] testArr3 = {8, 4, 23, 42, 16, 15};
        InsertionSort.insertionSort(testArr3);

    }
}
