/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App classUnderTest = new App();
    LinkedList newLinkedList = new LinkedList<Integer>();
    @Test void  instantiateAnEmptyLinkedList() {
        assertEquals(null,newLinkedList.head);
    }
    @Test void insertIntoTheLinkedList(){

        newLinkedList.insert(10);
        assertEquals("{ 10 } -> NULL",newLinkedList.toString());
    }
    @Test void pointToTheFirstNodeInTheLinkedList(){
        newLinkedList.insert(12);
        assertEquals(12,newLinkedList.head.value);
    }
    @Test void insertMultipleNodes(){
        newLinkedList.insert(5);
        newLinkedList.insert(4);
        newLinkedList.insert(20);
        assertEquals("{ 20 } -> { 4 } -> { 5 } -> NULL",newLinkedList.toString());
        assertEquals(20,newLinkedList.head.value);
        assertTrue(newLinkedList.includes(4));
    }
    @Test void isIncluded(){
        newLinkedList.insert(45);
        newLinkedList.insert(22);
        assertTrue(newLinkedList.includes(22));
        assertFalse(newLinkedList.includes(30));
    }
    @Test void testToString(){
        newLinkedList.insert(45);
        newLinkedList.insert(42);
        newLinkedList.insert(43);
        newLinkedList.insert(46);
        newLinkedList.insert(70);
        assertEquals("{ 70 } -> { 46 } -> { 43 } -> { 42 } -> { 45 } -> NULL",newLinkedList.toString());
    }
}
