/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {

    public static void main(String[] args) {
        LinkedList ahmedsLinkedList = new LinkedList<Integer>();
        ahmedsLinkedList.insert(10);
        ahmedsLinkedList.insert(5);
        ahmedsLinkedList.insert(6);
        ahmedsLinkedList.insert(10);

        System.out.println(ahmedsLinkedList.toString());

        System.out.println(ahmedsLinkedList.includes(8));

    }
}
